import assert from 'node:assert/strict';
import { test } from 'node:test';
import { EditorState } from '@codemirror/state';
import { EditorView } from '@codemirror/view';
const editor = await import('./build/hybrid-editor.mjs').catch(() => ({}));
const source = '## Heading ^ABCDEF\n#Claim\n\nText {ref:[[Book]]}\n\n![[Book]] %%ht%%\n';
const meta = {title:'Book',authors:[],dates:[],citationAuthors:['Bates'],publicationYear:'2022',publish:false,publicTitle:false};
const tree = {key:'Test:0',id:'ABCDEF',path:'Test.md',level:2,line:0,endLine:7,from:0,to:source.length,contentFrom:source.indexOf('Text'),meta:{...meta,title:'Heading',taxon:'Claim'},metadataRanges:[{from:source.indexOf('#Claim'),to:source.indexOf('#Claim')+6}],children:[],number:'1'};
const doc = {path:'Test.md',source,enabled:true,frontmatter:{},root:tree,trees:[tree],protectedRanges:[],raw:[],diagnostics:[]};
const host = {document:() => doc, resolve:() => ({status:'resolved',tree:{...tree,meta},document:doc}), renderEmbed:() => () => {}, open:() => {}};
test('real CodeMirror state provides replacements without modifying source, revealing a citation at the cursor', () => {
 assert.equal(typeof editor.createHybridEditor,'function');
 let state=EditorState.create({doc:source,extensions:editor.createHybridEditor(host)});
 const count=s => {let n=0; for(const ds of s.facet(EditorView.decorations)) if(typeof ds.between==='function') ds.between(0,s.doc.length,(_a,_b,v)=>{if(v.spec?.widget?.span?.kind==='citation')n++;}); return n;};
 assert.equal(count(state),1);
 assert.equal(state.doc.toString(),source);
 state=state.update({selection:{anchor:source.indexOf('{ref:')+2}}).state;
 assert.equal(count(state),0);
 assert.equal(state.doc.toString(),source);
});
test('real CodeMirror omits inline TOC while keeping source, numbered headings and embed decorations',async()=>{
 const {parseHybrid,indexHybrid,resolveHybrid}=await import('./build/hybrid-core.mjs');
 const {treeOutline}=await import('./build/hybrid-display.mjs');
 const options={folders:[],publicFolders:[],reservedIds:[]};
 const text='---\nforester-mode: true\nforester-id: AAAAAA\n---\n# Main\n\n![[Book]]\n\n## First ^ABCD01\n#Claim\n\nBody.\n\n### Child ^ABCD02\n\nChild body.\n';
 const parsed=parseHybrid('Main.md',text,options);
 const book=parseHybrid('Book.md','---\nforester-id: BBBBBB\n---\n# Book\n\nBook body.\n',options);
 const index=indexHybrid([parsed,book]);
 const resolve=(target,path='Main.md')=>resolveHybrid(index,target,path);
 const h={...host,document:()=>parsed,resolve};
 let state=EditorState.create({doc:text,selection:{anchor:text.length},extensions:editor.createHybridEditor(h)});
 const decorations=s=>{const values=[];for(const ds of s.facet(EditorView.decorations))if(typeof ds.between==='function')ds.between(0,s.doc.length,(_a,_b,v)=>values.push(v));return values;};
 const assertNoToc=s=>{
  const widgets=decorations(s).map(v=>v.spec.widget).filter(Boolean);
  assert.equal(widgets.some(widget=>widget.constructor.name==='TocWidget'),false,'no inline TocWidget');
  assert.equal(widgets.some(widget=>'entries' in widget),false,'no inline outline entries');
  assert.equal(s.doc.toString(),text);
 };
 assertNoToc(state);
 const values=decorations(state);
 assert.equal(values.filter(v=>v.spec.class==='hybrid-tree-heading').length,3);
 assert.deepEqual(values.map(v=>v.spec.widget?.label).filter(Boolean),['Claim 2','2.1']);
 assert.equal(values.filter(v=>v.spec.widget?.span?.kind==='embed').length,1);
 assert.equal(typeof treeOutline,'function','pure sidebar outline remains available');
 const outline=treeOutline(parsed,resolve);
 assert.deepEqual(outline.map(entry=>[entry.title,entry.number]),[['Book','1'],['First','2']]);
 assert.deepEqual(outline[1].children.map(entry=>[entry.title,entry.number]),[['Child','2.1']]);
 state=state.update({effects:editor.hybridRefresh.of(null)}).state;
 assertNoToc(state);
 state=state.update({selection:{anchor:text.indexOf('## First')}}).state;
 assertNoToc(state);
});
