import assert from 'node:assert/strict';import test from 'node:test';
import {access,readFile,readdir} from 'node:fs/promises';import {homedir} from 'node:os';import {join} from 'node:path';import {chromium} from 'playwright-core';
const theme=await readFile(new URL('../../theme.css',import.meta.url),'utf8'),plugin=await readFile(new URL('../styles.css',import.meta.url),'utf8');
async function executable(){if(process.env.HYBRID_CHROMIUM)return process.env.HYBRID_CHROMIUM;const cache=join(homedir(),'.cache/ms-playwright');for(const name of (await readdir(cache)).filter(s=>s.startsWith('chromium_headless_shell-')).sort().reverse()){const p=join(cache,name,'chrome-headless-shell-linux64/chrome-headless-shell');if(await access(p).then(()=>true,()=>false))return p;}throw Error('HYBRID_CHROMIUM or cached Chromium required');}
const html=mode=>`<!doctype html><meta charset="utf-8"><style>
body{font-size:16px;font-family:sans-serif;--text-normal:${mode==='light'?'#000':'#dcdcdc'};--text-muted:#666;--text-accent:#cf2a80;--text-error:#c00;--background-modifier-border:#aaa;color:var(--text-normal)}
h1{font-size:var(--h1-size,2em)}h2,h3{font-size:var(--h2-size,1.5em)}.markdown-rendered{font-family:var(--font-text-theme,serif)}
</style><body class="theme-${mode} forester-enabled"><p id="body">本文 Body</p><span id="size-reference" style="font-size:13pt">Reference</span>
<div class="markdown-rendered"><div class="hybrid-managed-embed"><div id="embed" class="hybrid-embed"><header class="hybrid-tree-header"><h1><span id="root" class="hybrid-taxon-number hybrid-root-taxon">Claim</span><span id="title">情報概念 Information</span> <a id="slug" class="hybrid-slug">[ABCDEF]</a></h1><div id="meta" class="hybrid-metadata"><ul><li>October 4, 2026</li><li>Alice</li></ul></div></header><div class="hybrid-tree-body"><h3 id="nested"><span class="hybrid-taxon-number">Claim 1</span>下位見出し</h3><p>日本語と English の本文。</p></div></div></div><div class="hybrid-embed hybrid-error" id="error">Diagnostic</div></div>
<div class="markdown-source-view mod-cm6 is-live-preview"><div class="cm-content"><div class="hybrid-header-taxon"><span class="hybrid-taxon-number hybrid-root-taxon">Claim</span></div><div class="cm-line HyperMD-header HyperMD-header-2 hybrid-tree-heading" id="lp-heading"><span class="hybrid-taxon-number">Claim 1</span>見出し</div><div class="hybrid-header-metadata"><div class="hybrid-metadata">Alice</div></div></div></div></body>`;
test('v2 companion theme styles hybrid headers, metadata and plain Forester transclusions in both CSS load orders',async t=>{
const browser=await chromium.launch({executablePath:await executable(),headless:true});try{
 for(const mode of ['light','dark'])for(const order of ['theme-first','plugin-first'])await t.test(`${mode} ${order}`,async()=>{
  const page=await browser.newPage();try{await page.setContent(html(mode));for(const css of order==='theme-first'?[theme,plugin]:[plugin,theme])await page.addStyleTag({content:css});await page.evaluate(()=>document.fonts.ready);
  const s=await page.evaluate(()=>{const el=id=>document.getElementById(id),style=id=>getComputedStyle(el(id));return {root:style('root').color,rootDisplay:style('root').display,above:el('root').getBoundingClientRect().bottom<=el('title').getBoundingClientRect().top,slug:style('slug').color,slugLine:style('slug').textDecorationLine,slugStyle:style('slug').textDecorationStyle,meta:style('meta').color,metaFont:style('meta').fontFamily,body:style('body').color,border:style('embed').borderLeftWidth,nested:style('nested').fontSize,lp:style('lp-heading').fontSize,reference:style('size-reference').fontSize,list:getComputedStyle(el('meta').querySelector('ul')).display,error:style('error').color,lpRoot:getComputedStyle(document.querySelector('.hybrid-header-taxon .hybrid-root-taxon')).color};});
  assert.equal(s.root,'rgb(136, 136, 136)');assert.equal(s.lpRoot,s.root);assert.equal(s.rootDisplay,'block');assert.ok(s.above);assert.equal(s.slug,s.root);assert.ok(s.slugLine.includes('underline'));assert.equal(s.slugStyle,'dotted');assert.equal(s.meta,s.body);assert.ok(s.metaFont.includes('BIZ UDMincho'));assert.equal(s.border,'0px');assert.equal(s.nested,s.reference);assert.equal(s.lp,s.reference);assert.equal(s.list,'inline');assert.equal(s.error,'rgb(204, 0, 0)');console.log(JSON.stringify({mode,order,...s}));
 }finally{await page.close();}});
}finally{await browser.close();}});
